<?php
/*
 * Welcome message for Inchoo ticket
 */
?>
<div class="welcome-msg">
    <p class="welcome"><?php echo $this->__('Welcome '); ?><strong><?php echo $this->getCustomerName(); ?></strong> <?php echo $this->__('to'); ?> <strong><?php echo $this->__('Inchoo Ticket Management system.'); ?></strong></p>
    <p><?php echo $this->__('Inchoo Ticket Management system is created for the learning purpose for the interns or new employees who are getting familiar with Magento.'); ?></p>
    <p><?php echo $this->__('This module has been created by Zoran Šalamun.'); ?></p>
</div>